class Constants:
    SUFFIX_PRINT_PAUSE = 'PAUSE'
    SUFFIX_PRINT_RESUME = 'RESUME'
    SUFFIX_PRINT_UNSTABLE = 'UNSTABLE'
    SUFFIX_PRINT_QUEUED = 'QUEUED'
    GCODE_TAG_STABILIZATION = 'timelapseplus-stabilization'
    GCODE_G90_G91_EXTRUDER_OVERWRITE = True
